Add files via upload

diff --git a/android/gradlew b/android/gradlew
--- a/android/gradlew
+++ b/android/gradlew
@@ -1,68 +1,59 @@
 #!/usr/bin/env sh
 
-##############################################################################
-# Gradle wrapper script
-##############################################################################
-
 APP_NAME="Gradle"
 APP_BASE_NAME=`basename "$0"`
-
-# Add default JVM options here
 DEFAULT_JVM_OPTS="-Xmx1024m -Xms256m"
-
-# Use the maximum available, or set MAX_FD != -1 to use that value
 MAX_FD="maximum"
 
-warn () {
-    echo "$*"
-}
+warn () { echo "$*"; }
+die () { echo; echo "$*"; echo; exit 1; }
 
-die () {
-    echo
-    echo "$*"
-    echo
-    exit 1
-}
-
-# OS specific support (must be 'true' or 'false').
 cygwin=false
 msys=false
 darwin=false
 nonstop=false
 case "`uname`" in
-  CYGWIN* )
-    cygwin=true
-    ;;
-  Darwin* )
-    darwin=true
-    ;;
-  MINGW* )
-    msys=true
-    ;;
-  NONSTOP* )
-    nonstop=true
-    ;;
+  CYGWIN* ) cygwin=true ;;
+  Darwin* ) darwin=true ;;
+  MINGW* ) msys=true ;;
+  NONSTOP* ) nonstop=true ;;
 esac
+
+SCRIPT="$0"
+while [ -h "$SCRIPT" ]; do
+  ls=`ls -ld "$SCRIPT"`
+  link=`expr "$ls" : '.*-> \(.*\)$'`
+  if expr "$link" : '/.*' > /dev/null; then
+    SCRIPT="$link"
+  else
+    SCRIPT=`dirname "$SCRIPT"`"/$link"
+  fi
+done
+APP_HOME=`dirname "$SCRIPT"`
+APP_HOME=`cd "$APP_HOME" && pwd`
 
 CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
 
-# Determine the Java command to use to start the JVM.
 if [ -n "$JAVA_HOME" ] ; then
-    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
-        JAVACMD="$JAVA_HOME/jre/sh/java"
-    else
-        JAVACMD="$JAVA_HOME/bin/java"
-    fi
-    if [ ! -x "$JAVACMD" ] ; then
-        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
-    fi
+  if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
+    JAVACMD="$JAVA_HOME/jre/sh/java"
+  else
+    JAVACMD="$JAVA_HOME/bin/java"
+  fi
+  if [ ! -x "$JAVACMD" ] ; then
+    die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
+  fi
 else
-    JAVACMD="java"
-    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
+  JAVACMD="java"
+  which java > /dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found."
 fi
 
-exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
-  "-Dorg.gradle.appname=$APP_BASE_NAME" \
+if [ "$cygwin" = "true" -o "$msys" = "true" ] ; then
+  APP_HOME=`cygpath --path --mixed "$APP_HOME"`
+  CLASSPATH=`cygpath --path --mixed "$CLASSPATH"`
+fi
+
+exec "$JAVACMD" $DEFAULT_JVM_OPTS \
   -classpath "$CLASSPATH" \
   org.gradle.wrapper.GradleWrapperMain \
   "$@"
